### ISSUE TITLE
SocketMC ERROR

### ISSUE THREAD

**Issue by 0xC1A551C** [RHazDev/Sockets4MC#1]
Using the latest version at this date on the latest version of bungee.

`> 03:19:52 [SEVERE] Exception disabling plugin Sockets4MC
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at fr.rhaz.minecraft.sockets.Sockets4MC.<clinit>(Sockets4MC.kt:50)
at fr.rhaz.minecraft.sockets.Sockets4Bungee.onDisable(Sockets4MC.kt:44)
at net.md_5.bungee.BungeeCord$4.run(BungeeCord.java:434)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 3 more`

With kotlin & cmddispatcher installed.

**Comment by hazae41** [comment]
Is Kotlin updated?

**Comment by 0xC1A551C** [comment]
Looks like it happened when I restarted the server without kotlin. My bad
